version: '3.8'

services:
  # 1. Database Relazionale (Postgres)
  omnimove-postgres:
    image: postgres:15-alpine
    container_name: omnimove-postgres-container
    ports:
      - "5433:5432" # Mappa la porta 5433 del PC alla 5432 del container
    environment:
      POSTGRES_DB: omnimovedb
      POSTGRES_USER: omnimove
      POSTGRES_PASSWORD: omnimove
    volumes:
      - omnimove_postgres_data:/var/lib/postgresql/data

  # 2. Database Temporale (InfluxDB)
  omnimove-influxdb:
    image: influxdb:2.7-alpine
    container_name: omnimove-influxdb-container
    ports:
      - "8087:8086" # Mappa la porta 8087 del PC alla 8086 del container
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=omnimove_admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password_influx_omnimove
      - DOCKER_INFLUXDB_INIT_ORG=omnimove_org
      - DOCKER_INFLUXDB_INIT_BUCKET=omnimove_bucket
    volumes:
      - omnimove_influxdb_data:/var/lib/influxdb2

  # 3. Cache / NoSQL (Redis)
  omnimove-redis:
    image: redis:7-alpine
    container_name: omnimove-redis-container
    ports:
      - "6380:6379" # Mappa la porta 6380 del PC alla 6379 del container
    volumes:
      - omnimove_redis_data:/data

volumes:
  omnimove_postgres_data:
  omnimove_influxdb_data:
  omnimove_redis_data: