ALTER TABLE stops ADD COLUMN active BOOLEAN DEFAULT true;
ALTER TABLE stops ADD COLUMN created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE stops ADD COLUMN description TEXT;
ALTER TABLE stops ADD COLUMN lat DOUBLE PRECISION NOT NULL;
ALTER TABLE stops ADD COLUMN lon DOUBLE PRECISION NOT NULL;
ALTER TABLE stops DROP COLUMN IF EXISTS latitude;
ALTER TABLE stops DROP COLUMN IF EXISTS longitude;

ALTER TABLE routes ADD COLUMN active BOOLEAN DEFAULT true;